### ISSUE TITLE
[REQUEST] Add Zigbee network backup to file and restore features to tzb-zigpy-cli-tools

### ISSUE THREAD

**Issue by Hedda** [tube0013/tubeszb_addons#2]
@tube0013 Please consider adding feature options Zigbee network backup to file and restore features to tzb-zigpy-cli-tools.

This would be especially helpful to Zigbee2MQTT users for adapter migration when they have Silicon Labs and ConBee/RaspBee based Zigbee Coordinator radio dongles as the zigbee-herdsman library Z2M depends on currently only support Texas Instruments based adapters.

Zigbee2MQTT users can already manually install and use zigpy-cli to create a manual backup to file of their Zigbee network from their old Zigbee Coordinator regardless of which radio type it is based on and then restore that backup from file to a new adapter. 

For example, a Zigbee network backup will allow you to migrate from a old TI CC2531 with Z-Stack Home 1.2 or an old Silabs EM35xx to a newer CC2652 or EFR32MG21 based Zigbee Coordinator without having to manually re-pair/re-join any devices.  You can even migrate from older ConBee and RaspBee (deconz firmware based) adapters as long as you first upgrade their firmware.

For reference see:

* https://github.com/Koenkk/zigbee2mqtt/discussions/16478
* https://github.com/Koenkk/zigbee-herdsman/issues/665
* https://github.com/Koenkk/zigbee-herdsman/issues/319

zigpy-cli can backup and restore Zigbee network to/from file allow Zigbee2MQTT users to backup and migrate radio types:

https://github.com/zigpy/zigpy-cli/blob/dev/README.md#network-backup

https://github.com/zigpy/zigpy-cli/blob/dev/README.md#network-restore

Note! Restoring backups using zigpy-cli automatically copy the same IEEE to a new adapter and that way the Zigbee gateway application thinks it is the same adapter, but the end user themselves would still need to manually change `serial `config for `port`, `adapter` (i.e. radio type), and/or `baudrate` in their `configuration.yaml` for Z2M config if they changed from for example Silicon Labs to Texas Instruments or firmware:

https://www.zigbee2mqtt.io/guide/faq/#how-do-i-migrate-from-one-adapter-to-another

https://www.zigbee2mqtt.io/guide/configuration/

PS: ZHA and Zigbee2MQTT gateway backups are not compatible even though both use "Open ZigBee Coordinator Backup Format" because the Zigbee network backup is only a high-level and stack-agnostic backup of your device's network data (written in the [Open Coordinator Backup Format](https://github.com/zigpy/open-coordinator-backup/)) but it at least allows you to snapshot the device state and move your network between any hardware and firmware versions supported by zigpy-cli. This backup format is human-readable and fully documented so users have to option to manually fill out or change the appropriate information by hand to form a network if they are migrating from a Zigbee Coordinator that is not currently supported.

https://github.com/zigpy/open-coordinator-backup

**Comment by tube0013** [comment]
Backup and Restore added in 0.2.2
