### ISSUE TITLE
[REQUEST] Look at patches from darkxst for his multipan flasher fork of the Silabs Flasher

### ISSUE THREAD

**Issue by Hedda** [tube0013/tubeszb_addons#7]
FYI, @darkxst has a downstream fork of Silabs Flasher add-on with patches that might be interested in looking at for your fork:

https://github.com/darkxst/multipan_flasher

https://github.com/darkxst/multipan_flasher/pulls?q=is%3Apr

https://github.com/darkxst/multipan_flasher/blob/main/multipan_flasher/DOCS.md

Thinking that perhaps him and you are also interested in collaborating on some patches from your own Silabs Flasher fork:

https://github.com/tube0013/tubeszb_addons/tree/main/tzb-silabs-flasher

https://github.com/tube0013/tubeszb_addons/blob/main/tzb-silabs-flasher/DOCS.md

**Comment by tube0013** [comment]
I've been following the work puddly is doing in creating manifests for the different builds and will adopt that when it is finalized.
